// lib/tradeConfig.js
// Adding a new trade = add one object here. No page changes needed.

const TRADE_CONFIGS = {
  gc: {
    name: 'General Contractor',
    shortName: 'GC',
    icon: '\u{1F3D7}\uFE0F',
    color: '#FF7A3D',
    colorRgb: '255,122,61',
    slug: 'gc',
    subtitle: 'Construction permit leads scored for general contractors',
    kpiLabels: ['Total Leads', 'Hot 75+', 'Destroyed', 'Est. Rebuild Value'],
    kpiIcons: ['layers', 'flame', 'alert', 'dollar'],
    kpiKeys: ['totalLeads', 'hotLeads', 'destroyed', 'rebuildValue'],
    kpiSubs: ['+5 today', null, null, null],
    briefLabel: 'Palisades Fire Intel',
    topLeadsLabel: 'Top leads by score',
    quickActions: [
      { href: '/outreach', label: 'Review outreach queue', sub: 'DRAFTS PENDING', icon: 'mail' },
      { href: '/map', label: 'View fire zone map', sub: 'ACTIVE LEADS', icon: 'map' },
    ],
    showTags: ['dins_damage', 'permit_type', 'permit_stage', 'permit_count'],
    intelLabel: 'Permit intel',
    sortDefault: 'score',
  },

  enviro: {
    name: 'Environmental Services',
    shortName: 'Enviro',
    icon: '\u2623\uFE0F',
    color: '#00C896',
    colorRgb: '0,200,150',
    slug: 'enviro',
    subtitle: 'Pre-1978 renovation and demolition leads scored for hazmat risk',
    kpiLabels: ['Pre-1978 Leads', 'High Risk 80+', 'New This Week', 'Est. Job Value'],
    kpiIcons: ['alert', 'flame', 'layers', 'dollar'],
    kpiKeys: ['totalLeads', 'hotLeads', 'newThisWeek', 'rebuildValue'],
    kpiSubs: ['Pre-1978 homes', 'Score 80+', 'Fresh permits', 'Abatement pipeline'],
    briefLabel: 'Environmental Intel',
    topLeadsLabel: 'Highest risk leads',
    quickActions: [
      { href: '/outreach', label: 'Review outreach queue', sub: 'DRAFTS PENDING', icon: 'mail' },
      { href: '/map', label: 'View pre-1978 map', sub: 'ACTIVE LEADS', icon: 'map' },
    ],
    showTags: ['year_built_tag', 'permit_type', 'risk_level', 'permit_count'],
    intelLabel: 'Hazmat intel',
    sortDefault: 'score',
  },

  roofing: {
    name: 'Roofing',
    shortName: 'Roofing',
    icon: '\u{1F3E0}',
    color: '#4A9EFF',
    colorRgb: '74,158,255',
    slug: 'roofing',
    subtitle: 'Roof replacement and repair leads scored for roofing contractors',
    kpiLabels: ['Total Leads', 'Full Reroof', 'New This Week', 'Est. Job Value'],
    kpiIcons: ['layers', 'flame', 'layers', 'dollar'],
    kpiKeys: ['totalLeads', 'hotLeads', 'newThisWeek', 'rebuildValue'],
    kpiSubs: [null, 'Score 80+', 'Fresh permits', 'Roofing pipeline'],
    briefLabel: 'Roofing Intel',
    topLeadsLabel: 'Top roofing leads',
    quickActions: [
      { href: '/outreach', label: 'Review outreach queue', sub: 'DRAFTS PENDING', icon: 'mail' },
      { href: '/map', label: 'View leads map', sub: 'ACTIVE LEADS', icon: 'map' },
    ],
    showTags: ['dins_damage', 'permit_type', 'roof_age', 'permit_count'],
    intelLabel: 'Roof intel',
    sortDefault: 'score',
  },

  solar: {
    name: 'Solar',
    shortName: 'Solar',
    icon: '\u2600\uFE0F',
    color: '#FFD43B',
    colorRgb: '255,212,59',
    slug: 'solar',
    subtitle: 'Solar installation leads scored for solar contractors',
    kpiLabels: ['Total Leads', 'Title 24 Required', 'New This Week', 'Est. System Value'],
    kpiIcons: ['layers', 'flame', 'layers', 'dollar'],
    kpiKeys: ['totalLeads', 'hotLeads', 'newThisWeek', 'rebuildValue'],
    kpiSubs: [null, 'New builds', 'Fresh permits', 'Solar pipeline'],
    briefLabel: 'Solar Intel',
    topLeadsLabel: 'Top solar leads',
    quickActions: [
      { href: '/outreach', label: 'Review outreach queue', sub: 'DRAFTS PENDING', icon: 'mail' },
      { href: '/map', label: 'View leads map', sub: 'ACTIVE LEADS', icon: 'map' },
    ],
    showTags: ['permit_type', 'sqft_tag', 'no_solar', 'permit_count'],
    intelLabel: 'Solar intel',
    sortDefault: 'score',
  },

  plumbing: {
    name: 'Plumbing',
    shortName: 'Plumbing',
    icon: '\u{1F6BF}',
    color: '#7C6AEF',
    colorRgb: '124,106,239',
    slug: 'plumbing',
    subtitle: 'Plumbing leads scored for re-pipe, water heater, and new construction',
    kpiLabels: ['Total Leads', 'Hot 75+', 'New This Week', 'Est. Job Value'],
    kpiIcons: ['layers', 'flame', 'layers', 'dollar'],
    kpiKeys: ['totalLeads', 'hotLeads', 'newThisWeek', 'rebuildValue'],
    kpiSubs: [null, 'Score 75+', 'Fresh permits', 'Plumbing pipeline'],
    briefLabel: 'Plumbing Intel',
    topLeadsLabel: 'Top plumbing leads',
    quickActions: [
      { href: '/outreach', label: 'Review outreach queue', sub: 'DRAFTS PENDING', icon: 'mail' },
      { href: '/map', label: 'View leads map', sub: 'ACTIVE LEADS', icon: 'map' },
    ],
    showTags: ['year_built_tag', 'permit_type', 'permit_stage', 'permit_count'],
    intelLabel: 'Plumbing intel',
    sortDefault: 'score',
  },

  hvac: {
    name: 'HVAC',
    shortName: 'HVAC',
    icon: '\u2744\uFE0F',
    color: '#3B9AE1',
    colorRgb: '59,154,225',
    slug: 'hvac',
    subtitle: 'HVAC leads scored for system install and replacement',
    kpiLabels: ['Total Leads', 'Hot 75+', 'New This Week', 'Est. Job Value'],
    kpiIcons: ['layers', 'flame', 'layers', 'dollar'],
    kpiKeys: ['totalLeads', 'hotLeads', 'newThisWeek', 'rebuildValue'],
    kpiSubs: [null, 'Score 75+', 'Fresh permits', 'HVAC pipeline'],
    briefLabel: 'HVAC Intel',
    topLeadsLabel: 'Top HVAC leads',
    quickActions: [
      { href: '/outreach', label: 'Review outreach queue', sub: 'DRAFTS PENDING', icon: 'mail' },
      { href: '/map', label: 'View leads map', sub: 'ACTIVE LEADS', icon: 'map' },
    ],
    showTags: ['permit_type', 'permit_stage', 'sqft_tag', 'permit_count'],
    intelLabel: 'HVAC intel',
    sortDefault: 'score',
  },

  electrical: {
    name: 'Electrical',
    shortName: 'Electrical',
    icon: '\u26A1',
    color: '#F59E0B',
    colorRgb: '245,158,11',
    slug: 'electrical',
    subtitle: 'Electrical leads scored for panel upgrades, rewiring, and EV chargers',
    kpiLabels: ['Total Leads', 'Hot 75+', 'New This Week', 'Est. Job Value'],
    kpiIcons: ['layers', 'flame', 'layers', 'dollar'],
    kpiKeys: ['totalLeads', 'hotLeads', 'newThisWeek', 'rebuildValue'],
    kpiSubs: [null, 'Score 75+', 'Fresh permits', 'Electrical pipeline'],
    briefLabel: 'Electrical Intel',
    topLeadsLabel: 'Top electrical leads',
    quickActions: [
      { href: '/outreach', label: 'Review outreach queue', sub: 'DRAFTS PENDING', icon: 'mail' },
      { href: '/map', label: 'View leads map', sub: 'ACTIVE LEADS', icon: 'map' },
    ],
    showTags: ['year_built_tag', 'permit_type', 'permit_stage', 'permit_count'],
    intelLabel: 'Electrical intel',
    sortDefault: 'score',
  },

  publicadjuster: {
    name: 'Public Adjuster',
    shortName: 'Adjuster',
    icon: '\u{1F4CB}',
    color: '#E05252',
    colorRgb: '224,82,82',
    slug: 'publicadjuster',
    subtitle: 'Insurance claim leads scored for public adjusters',
    kpiLabels: ['Total Leads', 'Destroyed', 'High Value', 'Est. Claim Value'],
    kpiIcons: ['layers', 'alert', 'flame', 'dollar'],
    kpiKeys: ['totalLeads', 'destroyed', 'hotLeads', 'rebuildValue'],
    kpiSubs: [null, 'Fire damaged', 'Score 80+', 'Total pipeline'],
    briefLabel: 'Adjuster Intel',
    topLeadsLabel: 'Highest value claims',
    quickActions: [
      { href: '/outreach', label: 'Review outreach queue', sub: 'DRAFTS PENDING', icon: 'mail' },
      { href: '/map', label: 'View fire zone map', sub: 'ACTIVE LEADS', icon: 'map' },
    ],
    showTags: ['dins_damage', 'assessor_value_tag', 'owner_occupied', 'permit_count'],
    intelLabel: 'Claim intel',
    sortDefault: 'score',
  },
}

export function getTradeConfig(trade) {
  return TRADE_CONFIGS[trade] || TRADE_CONFIGS.gc
}

export function getAllTrades() {
  return Object.entries(TRADE_CONFIGS).map(([slug, config]) => ({
    slug,
    name: config.name,
    icon: config.icon,
    color: config.color,
  }))
}

export default TRADE_CONFIGS
